server {
    listen 80;
    server_name _;
    
     # ตั้งค่าขนาดไฟล์สูงสุดที่อนุญาตให้อัปโหลด
    client_max_body_size 50M;

    root /usr/share/nginx/html;
    index index.html;

    # Serve Angular routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optionally: proxy API
    location /api/ {
        proxy_pass http://server:3000/api/;
    }
}
